[package]
name = "spice21int"
version = "0.1.5"
authors = [
    "Dan Fritchman <dan@fritch.mn>",
    "HW21 <hw21@hw21.io>"
]
edition = "2018"
license = "BSD-3-Clause"
description = "Spice21 Internal Crate, for Proc-Macro Separation. Not helpful for anyone else."

[dependencies]
prost = "0.6.1"
