[package]
name = "spice21"
version = "0.1.0"
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Coming Soon"

[dependencies]
serde = "1.0"
serde_json = "1.0"
bytes = "0.5.4"
prost = "0.6.1"
prost-types = "0.6.1"
num = "0.3.0"
enum_dispatch = "0.3.1"

[build-dependencies]
prost-build = "0.6.1"
