[package]
name = "spice21"
version = "0.1.0"
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Coming Soon"

[dependencies]
sparse21 = { path = "../../sparse21" }
