
max_width = 150
single_line_if_else_max_width = 150 

# All of these highly desirable options require `nightly`. 
# Skip em for now. 
##empty_item_single_line = true
##fn_single_line = true
##struct_lit_single_line = true
