[package]
name = "spice21opentechs"
version = "0.1.0"
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"

[dependencies]
spice21 = { package="spice21", version="0.1.5", path = "../spice21" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.88"
serde_yaml = "0.8"
