
name: spice21js
on: [push, pull_request]

jobs:
  name: spice21js (${{ matrix.os }})
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn test
