# Nightly Run of Active Versions from Package Repositories 

name: Nightly
on: [push, pull_request] # To test this out
# on:
#   schedule:
#   - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  cargo:
    name: Cargo Install 
    runs-on: ubuntu-latest
    steps:
      - name: Install Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo Install 
        run: cargo install spice21 
        continue-on-error: true  # FIXME: remove. No binaries for it to install yet. 
        