
name: spice21py
on: [push, pull_request]

jobs:
  pytest:
    name: pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: checkout
        uses: actions/checkout@v1 
      - name: proto-deps
        run: |
          sudo apt install -y protobuf-compiler
          protoc --version  ## FIXME: doesn't find the well-known types e.g. DoubleValue yet 
      - name: py-deps
        working-directory: ./spice21py 
        run: |
          conda install -y pip cffi pytest protobuf 
          pip install maturin 
      - name: protoc
        run: |
          protoc -I=spice21/src --python_out=spice21py/spice21py spice21/src/*.proto 
          2to3 -wn -f import spice21py/spice21py/*pb2* 
      - name: build 
        working-directory: ./spice21py 
        run: maturin develop
      - name: test
        working-directory: ./spice21py 
        run: pytest 
      
      # - uses: actions/upload-artifact@v1
      #   name: upload-wheel
      #   with:
      #     name: wheel-${{ matrix.platform }}
      #     path: target/wheels/
        