# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: test
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        working-directory: ./spice21
        continue-on-error: true  # FIXME: remove
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        working-directory: ./spice21
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        working-directory: ./spice21
        continue-on-error: true  # FIXME: remove
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        working-directory: ./spice21
        continue-on-error: true  # FIXME: remove
        run: cargo clippy -- -D warnings
